// PLAITS.h - Arduino wrapper for Mutable Instruments Braids
// Note all the originals sources, .cc files, are retained and a copy with .inc extension has been made
//
#ifndef PLAITS_ARDUINO_H_
#define PLAITS_ARDUINO_H_

#include "plaits/resources.h"
#include "plaits/dsp/voice.h"
#include "plaits/dsp/speech/lpc_speech_synth.h"
#include "plaits/dsp/speech/lpc_speech_synth_controller.h"
#include "plaits/dsp/speech/lpc_speech_synth_words.h"
#include "plaits/dsp/speech/naive_speech_synth.h"
#include "plaits/dsp/speech/sam_speech_synth.h"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/dsp.h"
#include "plaits/dsp/engine/additive_engine.h"
#include "plaits/dsp/engine/bass_drum_engine.h"
#include "plaits/dsp/engine/chord_engine.h"
#include "plaits/dsp/engine/engine.h"
#include "plaits/dsp/engine/fm_engine.h"
#include "plaits/dsp/engine/grain_engine.h"
#include "plaits/dsp/engine/hi_hat_engine.h"
#include "plaits/dsp/engine/modal_engine.h"
#include "plaits/dsp/engine/noise_engine.h"
#include "plaits/dsp/engine/particle_engine.h"
#include "plaits/dsp/engine/snare_drum_engine.h"
#include "plaits/dsp/engine/speech_engine.h"
#include "plaits/dsp/engine/string_engine.h"
#include "plaits/dsp/engine/swarm_engine.h"
#include "plaits/dsp/engine/virtual_analog_engine.h"
#include "plaits/dsp/engine/waveshaping_engine.h"
#include "plaits/dsp/engine/wavetable_engine.h"
#include "plaits/dsp/engine/wave_terrain_engine.h"
#include "plaits/dsp/envelope.h"
#include "plaits/dsp/fx/diffuser.h"
#include "plaits/dsp/fx/fx_engine.h"
#include "plaits/dsp/fx/low_pass_gate.h"
#include "plaits/dsp/fx/overdrive.h"
#include "plaits/dsp/fx/sample_rate_reducer.h"
#include "plaits/dsp/noise/clocked_noise.h"
#include "plaits/dsp/noise/dust.h"
#include "plaits/dsp/noise/fractal_random_generator.h"
#include "plaits/dsp/noise/particle.h"
#include "plaits/dsp/noise/smooth_random_generator.h"
#include "plaits/dsp/oscillator/formant_oscillator.h"
#include "plaits/dsp/oscillator/grainlet_oscillator.h"
#include "plaits/dsp/oscillator/harmonic_oscillator.h"
#include "plaits/dsp/oscillator/oscillator.h"
#include "plaits/dsp/oscillator/sine_oscillator.h"
#include "plaits/dsp/oscillator/string_synth_oscillator.h"
#include "plaits/dsp/oscillator/variable_saw_oscillator.h"
#include "plaits/dsp/oscillator/variable_shape_oscillator.h"
#include "plaits/dsp/oscillator/vosim_oscillator.h"
#include "plaits/dsp/oscillator/wavetable_oscillator.h"
#include "plaits/dsp/oscillator/z_oscillator.h"
#include "plaits/dsp/physical_modelling/delay_line.h"
#include "plaits/dsp/physical_modelling/modal_voice.h"
#include "plaits/dsp/physical_modelling/resonator.h"
#include "plaits/dsp/physical_modelling/string.h"
#include "plaits/dsp/physical_modelling/string_voice.h"

#endif // PLAITS_ARDUINO_H_
